### ISSUE TITLE
Need little help

### ISSUE THREAD

**Issue by onlinecheckwriter-zz** [mamchyts/quickbooks#1]
1. https://developer-static.intuit.com/qbSDK-current/Common/newOSR/index.html Not found , where we will get it?
2. we run client.php but nothing is coming is it because we are using SDK13.0 ? any idea
3. can you add a example to add client/ view client etc.

**Comment by mamchyts** [comment]
Hi, 
code from the repo is very old. You can see the latest commit: `on Nov 1, 2013`
In the 2013 year - PHP sdk was not present yet. And we have only one way for integration -  web connector (https://developer.intuit.com/app/developer/qbdesktop/docs/get-started/get-started-with-quickbooks-web-connector)
Since 2013 - I don't work with QC.

I am not sure that web connector it a good solution for integration now.
You must use PHP sdk (https://github.com/intuit/QuickBooks-V3-PHP-SDK). 

Sorry, but I can't help you.
